In [11]:
import numpy as np
import pandas as pd

In [8]:
mat1 = np.ones((3,4))
print(mat1)
print("="*20)
mat2 = np.zeros((5,3))
print(mat2)
np.savez('np_file.npz', cat = mat1, dog = mat2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
with np.load('np_file.npz') as file:
    mat1 = file['cat']
    mat2 = file['dog']
 
print(mat1)
print("="*20)
print(mat2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [17]:
data = [[1,444,'abc'],
        [2,555,'def'],
        [3,666,'ghi'],
        [4,444,'xyz']]

df = pd.DataFrame(data)
type(data)
df

,0,1,2
0,1,444,abc
1,2,555,def
2,3,666,ghi
3,4,444,xyz


In [23]:
data = [[1,444,'abc'],
        [2,555,'def'],
        [3,666,'ghi'],
        [4,444,'xyz']]
 
data2 = {'id':[1,2,3,4],
        'sal':[444,555,666,444],
        'dep':['abc','def','ghi','xyz']}
df = pd.DataFrame(data2)
type(df)

pandas.DataFrame

In [24]:
display(df)

,id,sal,dep
0,1,444,abc
1,2,555,def
2,3,666,ghi
3,4,444,xyz


In [25]:
df.describe()

,id,sal
count,4.000000,4.000000
mean,2.500000,527.250000
std,1.290994,106.274409
min,1.000000,444.000000
25%,1.750000,444.000000
50%,2.500000,499.500000
75%,3.250000,582.750000
max,4.000000,666.000000


In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      4 non-null      int64
 1   sal     4 non-null      int64
 2   dep     4 non-null      str  
dtypes: int64(2), str(1)
memory usage: 228.0 bytes


In [27]:
df.values

array([[1, 444, 'abc'],
       [2, 555, 'def'],
       [3, 666, 'ghi'],
       [4, 444, 'xyz']], dtype=object)